# Step-by-step guide to compare techniques
Create a new Jupyter Notebook. You can call it “fine_tuning_comparion”. Make sure you have the appropriate Python kernel selected.

The remaining of this reading will guide you through the following steps:

Step 1: Prepare your dataset

Step 2: Apply traditional fine-tuning

Step 3: Fine-tune with LoRA

Step 4: Fine-tune with QLoRA

Step 5: Compare and analyze results

# Step 1: Prepare your dataset
The first step is to prepare your dataset for fine-tuning. You will use the same dataset for all three techniques to ensure a fair comparison.

Instructions
Load a sample dataset from scikit-learn and inspect its structure.

Apply preprocessing steps such as cleaning and tokenizing (use the BERT tokenizer) the full dataset before splitting it into sets. This ensures consistent preparation across the entire dataset and avoids data leakage.

Split the dataset into training, validation, and test sets.

Code example

#Step 2: Apply traditional fine-tuning
In the first part of the activity, you will apply traditional fine-tuning to the pretrained model. This involves updating all the parameters of the model during training.

Instructions


1.  Load a pretrained model (e.g., BERT or GPT).
2.  Fine-tune the entire model on the task-specific dataset.
3.  Record the training time, memory usage, and evaluation metrics.

Code example

Record
Training time: initialize a timer before each training block to print a message when training is complete.

Memory usage: use monitoring tools (e.g., nvidia-smi) to track memory consumption.

Model performance: print each performance metric (accuracy, precision, recall, F1 score) to the console after each block to compare between methods.

Step 3: Fine-tune with LoRA
Next, you will fine-tune the model using LoRA. This technique updates only low-rank matrices added to certain layers while freezing the rest of the model’s parameters.

Instructions
Import the necessary libraries, ensure the correct kernel is selected and tokenize the data set.

Install the peft package.

Initialize the BERT model and then define a LoRa configuration, define the rank of the update matrices and the alpha scaling factor.

Apply LoRA to specific layers of the pretrained model (e.g., attention layers).

Create a LoRa model using peft and set the number of training epochs.

Initialize a data collator, initialize a trainer, and then you can train the model.

Fine-tune only the low-rank matrices while keeping the other parameters frozen.

Record the same metrics as in traditional fine-tuning.

Code example

# Step 4: Fine-tune with QLoRA
Finally, you will apply QLoRA to the pretrained model. QLoRA quantizes the model’s parameters to reduce memory usage even further and fine-tunes only low-rank matrices.

Instructions
Import the necessary libraries, ensure the correct kernel is selected and tokenize the data set.

Quantize the pretrained model to reduce the memory footprint.

Apply LoRA to the quantized model’s layers.

Fine-tune the model and record the metrics.

**REVISED PROJECT**

In [14]:
import torch
import transformers
import datasets
import peft
import accelerate

print("Torch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("PEFT:", peft.__version__)
print("Accelerate:", accelerate.__version__)

Torch: 2.2.2
Transformers: 4.57.6
Datasets: 5.0.0
PEFT: 0.19.1
Accelerate: 1.14.0

In [15]:
import subprocess, sys
result = subprocess.run(
    [sys.executable, "-m", "pip", "install", "--upgrade", "scikit-learn"],
    capture_output=True, text=True
)
print(result.stdout[-2000:])
print(result.stderr[-2000:])

Requirement already satisfied: scikit-learn in /Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages (1.9.0)

error: invalid-installed-package

× Cannot process installed package numpy None in '/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages' because it has an invalid version:
│ Invalid version: '1.26.4 2'
╰─> Starting with pip 24.1, packages with invalid versions can not be processed.

hint: To proceed this package must be uninstalled.

In [16]:
import subprocess, sys
result = subprocess.run([sys.executable, "-m", "pip", "show", "scikit-learn", "numpy"], capture_output=True, text=True)
print(result.stdout)

Name: scikit-learn
Version: 1.9.0
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author:
Author-email:
License-Expression: BSD-3-Clause
Location: /Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages
Requires: joblib, narwhals, numpy, scipy, threadpoolctl
Required-by:
---

In [17]:
import subprocess, sys
result = subprocess.run(
    [sys.executable, "-m", "pip", "install", "numpy<2", "--force-reinstall", "--no-deps"],
    capture_output=True, text=True
)
print(result.stdout[-2000:])
print(result.stderr[-2000:])

Collecting numpy<2
  Using cached numpy-1.26.4-cp312-cp312-macosx_10_9_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-macosx_10_9_x86_64.whl (20.3 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy None

isimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 684, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/req/req_uninstall.py", line 523, in from_dist
    for path in uninstallation_paths(dist):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/req/req_uninstall.py", line 49, in unique
    for item in fn(*args, **kw):
                ^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/req/req_uninstall.py", line 77, in uninstallation_paths
    raise UninstallMissingRecord(distribution=dist)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/exceptions.py", line 769, in __init__
    dep = f"{distribution.raw_name}=={distribution.version}"
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_dists.py", line 174, in version
    return parse_version(version)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_vendor/packaging/version.py", line 122, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_vendor/packaging/version.py", line 438, in __init__
    raise InvalidVersion(f"Invalid version: {version!r}")
pip._vendor.packaging.version.InvalidVersion: Invalid version: '1.26.4 2'

In [18]:
import numpy, sklearn, torch, transformers, peft, datasets
print("numpy:", numpy.__version__)
print("sklearn:", sklearn.__version__)
print("torch:", torch.__version__)
print("transformers:", transformers.__version__)
print("peft:", peft.__version__)
print("datasets:", datasets.__version__)

numpy: 1.26.4
sklearn: 1.9.0
torch: 2.2.2
transformers: 4.57.6
peft: 0.19.1
datasets: 5.0.0

In [19]:
import subprocess, sys
result = subprocess.run([sys.executable, "-m", "pip", "show", "scipy", "joblib", "threadpoolctl", "narwhals"], capture_output=True, text=True)
print(result.stdout)

Name: scipy
Version: 1.17.1
Summary: Fundamental algorithms for scientific computing in Python
Home-page: https://scipy.org/
Author:
Author-email:
License: Copyright (c) 2001-2002 Enthought, Inc. 2003, SciPy Developers.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:

 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above
    copyright notice, this list of conditions and the following
    disclaimer in the documentation and/or other materials provided
    with the distribution.

 3. Neither the name of the copyright holder nor the names of its
    contributors may be used to endorse or promote products derived
    from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 ----

 This binary distribution of SciPy can also bundle the following software
 (depending on the build):


 Name: OpenBLAS
 Files: scipy/.dylibs/libscipy_openblas*.so
 Description: bundled as a dynamically linked library
 Availability: https://github.com/OpenMathLib/OpenBLAS/
 License: BSD-3-Clause
   Copyright (c) 2011-2014, The OpenBLAS Project
   All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are
   met:

      1. Redistributions of source code must retain the above copyright
         notice, this list of conditions and the following disclaimer.

      2. Redistributions in binary form must reproduce the above copyright
         notice, this list of conditions and the following disclaimer in
         the documentation and/or other materials provided with the
         distribution.
      3. Neither the name of the OpenBLAS project nor the names of
         its contributors may be used to endorse or promote products
         derived from this software without specific prior written
         permission.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
   SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
   USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


 Name: LAPACK
 Files: scipy/.dylibs/libscipy_openblas*.so
 Description: bundled in OpenBLAS
 Availability: https://github.com/OpenMathLib/OpenBLAS/
 License: BSD-3-Clause-Open-MPI
   Copyright (c) 1992-2013 The University of Tennessee and The University
                           of Tennessee Research Foundation.  All rights
                           reserved.
   Copyright (c) 2000-2013 The University of California Berkeley. All
                           rights reserved.
   Copyright (c) 2006-2013 The University of Colorado Denver.  All rights
                           reserved.

   $COPYRIGHT$

   Additional copyrights may follow

   $HEADER$

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are
   met:

   - Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.

   - Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer listed
     in this license in the documentation and/or other materials
     provided with the distribution.

   - Neither the name of the copyright holders nor the names of its
     contributors may be used to endorse or promote products derived from
     this software without specific prior written permission.

   The copyright holders provide no reassurances that the source code
   provided does not infringe any patent, copyright, or any other
   intellectual property rights of third parties.  The copyright holders
   disclaim any liability to any recipient for claims brought against
   recipient by any third party for infringement of that parties
   intellectual property rights.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
   OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


 Name: GCC runtime library
 Files: scipy/.dylibs/libgfortran*, scipy/.dylibs/libgcc*
 Description: dynamically linked to files compiled with gcc
 Availability: https://gcc.gnu.org/git/?p=gcc.git;a=tree;f=libgfortran
 License: GPL-3.0-or-later WITH GCC-exception-3.1
   Copyright (C) 2002-2017 Free Software Foundation, Inc.

   Libgfortran is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   Libgfortran is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   Under Section 7 of GPL version 3, you are granted additional
   permissions described in the GCC Runtime Library Exception, version
   3.1, as published by the Free Software Foundation.

   You should have received a copy of the GNU General Public License and
   a copy of the GCC Runtime Library Exception along with this program;
   see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
   <http://www.gnu.org/licenses/>.

 ----

 Full text of license texts referred to above follows (that they are
 listed below does not necessarily imply the conditions apply to the
 present binary release):

 ----

 GCC RUNTIME LIBRARY EXCEPTION

 Version 3.1, 31 March 2009

 Copyright (C) 2009 Free Software Foundation, Inc. <http://fsf.org/>

 Everyone is permitted to copy and distribute verbatim copies of this
 license document, but changing it is not allowed.

 This GCC Runtime Library Exception ("Exception") is an additional
 permission under section 7 of the GNU General Public License, version
 3 ("GPLv3"). It applies to a given file (the "Runtime Library") that
 bears a notice placed by the copyright holder of the file stating that
 the file is governed by GPLv3 along with this Exception.

 When you use GCC to compile a program, GCC may combine portions of
 certain GCC header files and runtime libraries with the compiled
 program. The purpose of this Exception is to allow compilation of
 non-GPL (including proprietary) programs to use, in this way, the
 header files and runtime libraries covered by this Exception.

 0. Definitions.

 A file is an "Independent Module" if it either requires the Runtime
 Library for execution after a Compilation Process, or makes use of an
 interface provided by the Runtime Library, but is not otherwise based
 on the Runtime Library.

 "GCC" means a version of the GNU Compiler Collection, with or without
 modifications, governed by version 3 (or a specified later version) of
 the GNU General Public License (GPL) with the option of using any
 subsequent versions published by the FSF.

 "GPL-compatible Software" is software whose conditions of propagation,
 modification and use would permit combination with GCC in accord with
 the license of GCC.

 "Target Code" refers to output from any compiler for a real or virtual
 target processor architecture, in executable form or suitable for
 input to an assembler, loader, linker and/or execution
 phase. Notwithstanding that, Target Code does not include data in any
 format that is used as a compiler intermediate representation, or used
 for producing a compiler intermediate representation.

 The "Compilation Process" transforms code entirely represented in
 non-intermediate languages designed for human-written code, and/or in
 Java Virtual Machine byte code, into Target Code. Thus, for example,
 use of source code generators and preprocessors need not be considered
 part of the Compilation Process, since the Compilation Process can be
 understood as starting with the output of the generators or
 preprocessors.

 A Compilation Process is "Eligible" if it is done using GCC, alone or
 with other GPL-compatible software, or if it is done without using any
 work based on GCC. For example, using non-GPL-compatible Software to
 optimize any GCC intermediate representations would not qualify as an
 Eligible Compilation Process.

 1. Grant of Additional Permission.

 You have permission to propagate a work of Target Code formed by
 combining the Runtime Library with Independent Modules, even if such
 propagation would otherwise violate the terms of GPLv3, provided that
 all Target Code was generated by Eligible Compilation Processes. You
 may then convey such a combination under terms of your choice,
 consistent with the licensing of the Independent Modules.

 2. No Weakening of GCC Copyleft.

 The availability of this Exception does not imply any general
 presumption that third-party software is unaffected by the copyleft
 requirements of the license of GCC.

 ----

                     GNU GENERAL PUBLIC LICENSE
                        Version 3, 29 June 2007

  Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
  Everyone is permitted to copy and distribute verbatim copies
  of this license document, but changing it is not allowed.

                             Preamble

   The GNU General Public License is a free, copyleft license for
 software and other kinds of works.

   The licenses for most software and other practical works are designed
 to take away your freedom to share and change the works.  By contrast,
 the GNU General Public License is intended to guarantee your freedom to
 share and change all versions of a program--to make sure it remains free
 software for all its users.  We, the Free Software Foundation, use the
 GNU General Public License for most of our software; it applies also to
 any other work released this way by its authors.  You can apply it to
 your programs, too.

   When we speak of free software, we are referring to freedom, not
 price.  Our General Public Licenses are designed to make sure that you
 have the freedom to distribute copies of free software (and charge for
 them if you wish), that you receive source code or can get it if you
 want it, that you can change the software or use pieces of it in new
 free programs, and that you know you can do these things.

   To protect your rights, we need to prevent others from denying you
 these rights or asking you to surrender the rights.  Therefore, you have
 certain responsibilities if you distribute copies of the software, or if
 you modify it: responsibilities to respect the freedom of others.

   For example, if you distribute copies of such a program, whether
 gratis or for a fee, you must pass on to the recipients the same
 freedoms that you received.  You must make sure that they, too, receive
 or can get the source code.  And you must show them these terms so they
 know their rights.

   Developers that use the GNU GPL protect your rights with two steps:
 (1) assert copyright on the software, and (2) offer you this License
 giving you legal permission to copy, distribute and/or modify it.

   For the developers' and authors' protection, the GPL clearly explains
 that there is no warranty for this free software.  For both users' and
 authors' sake, the GPL requires that modified versions be marked as
 changed, so that their problems will not be attributed erroneously to
 authors of previous versions.

   Some devices are designed to deny users access to install or run
 modified versions of the software inside them, although the manufacturer
 can do so.  This is fundamentally incompatible with the aim of
 protecting users' freedom to change the software.  The systematic
 pattern of such abuse occurs in the area of products for individuals to
 use, which is precisely where it is most unacceptable.  Therefore, we
 have designed this version of the GPL to prohibit the practice for those
 products.  If such problems arise substantially in other domains, we
 stand ready to extend this provision to those domains in future versions
 of the GPL, as needed to protect the freedom of users.

   Finally, every program is threatened constantly by software patents.
 States should not allow patents to restrict development and use of
 software on general-purpose computers, but in those that do, we wish to
 avoid the special danger that patents applied to a free program could
 make it effectively proprietary.  To prevent this, the GPL assures that
 patents cannot be used to render the program non-free.

   The precise terms and conditions for copying, distribution and
 modification follow.

                        TERMS AND CONDITIONS

   0. Definitions.

   "This License" refers to version 3 of the GNU General Public License.

   "Copyright" also means copyright-like laws that apply to other kinds of
 works, such as semiconductor masks.

   "The Program" refers to any copyrightable work licensed under this
 License.  Each licensee is addressed as "you".  "Licensees" and
 "recipients" may be individuals or organizations.

   To "modify" a work means to copy from or adapt all or part of the work
 in a fashion requiring copyright permission, other than the making of an
 exact copy.  The resulting work is called a "modified version" of the
 earlier work or a work "based on" the earlier work.

   A "covered work" means either the unmodified Program or a work based
 on the Program.

   To "propagate" a work means to do anything with it that, without
 permission, would make you directly or secondarily liable for
 infringement under applicable copyright law, except executing it on a
 computer or modifying a private copy.  Propagation includes copying,
 distribution (with or without modification), making available to the
 public, and in some countries other activities as well.

   To "convey" a work means any kind of propagation that enables other
 parties to make or receive copies.  Mere interaction with a user through
 a computer network, with no transfer of a copy, is not conveying.

   An interactive user interface displays "Appropriate Legal Notices"
 to the extent that it includes a convenient and prominently visible
 feature that (1) displays an appropriate copyright notice, and (2)
 tells the user that there is no warranty for the work (except to the
 extent that warranties are provided), that licensees may convey the
 work under this License, and how to view a copy of this License.  If
 the interface presents a list of user commands or options, such as a
 menu, a prominent item in the list meets this criterion.

   1. Source Code.

   The "source code" for a work means the preferred form of the work
 for making modifications to it.  "Object code" means any non-source
 form of a work.

   A "Standard Interface" means an interface that either is an official
 standard defined by a recognized standards body, or, in the case of
 interfaces specified for a particular programming language, one that
 is widely used among developers working in that language.

   The "System Libraries" of an executable work include anything, other
 than the work as a whole, that (a) is included in the normal form of
 packaging a Major Component, but which is not part of that Major
 Component, and (b) serves only to enable use of the work with that
 Major Component, or to implement a Standard Interface for which an
 implementation is available to the public in source code form.  A
 "Major Component", in this context, means a major essential component
 (kernel, window system, and so on) of the specific operating system
 (if any) on which the executable work runs, or a compiler used to
 produce the work, or an object code interpreter used to run it.

   The "Corresponding Source" for a work in object code form means all
 the source code needed to generate, install, and (for an executable
 work) run the object code and to modify the work, including scripts to
 control those activities.  However, it does not include the work's
 System Libraries, or general-purpose tools or generally available free
 programs which are used unmodified in performing those activities but
 which are not part of the work.  For example, Corresponding Source
 includes interface definition files associated with source files for
 the work, and the source code for shared libraries and dynamically
 linked subprograms that the work is specifically designed to require,
 such as by intimate data communication or control flow between those
 subprograms and other parts of the work.

   The Corresponding Source need not include anything that users
 can regenerate automatically from other parts of the Corresponding
 Source.

   The Corresponding Source for a work in source code form is that
 same work.

   2. Basic Permissions.

   All rights granted under this License are granted for the term of
 copyright on the Program, and are irrevocable provided the stated
 conditions are met.  This License explicitly affirms your unlimited
 permission to run the unmodified Program.  The output from running a
 covered work is covered by this License only if the output, given its
 content, constitutes a covered work.  This License acknowledges your
 rights of fair use or other equivalent, as provided by copyright law.

   You may make, run and propagate covered works that you do not
 convey, without conditions so long as your license otherwise remains
 in force.  You may convey covered works to others for the sole purpose
 of having them make modifications exclusively for you, or provide you
 with facilities for running those works, provided that you comply with
 the terms of this License in conveying all material for which you do
 not control copyright.  Those thus making or running the covered works
 for you must do so exclusively on your behalf, under your direction
 and control, on terms that prohibit them from making any copies of

In [20]:
# ============================================================
# fine_tuning_comparison.ipynb
# Dataset: IMDb sentiment (subset) via HuggingFace datasets
# ============================================================

# ── CELL 1: Install dependencies ──────────────────────────
#!pip install torch torchvision --force-reinstall --index-url https://download.pytorch.org/whl/cpu -q
#!pip install --upgrade transformers datasets peft accelerate bitsandbytes huggingface_hub -q

# ── CELL 2: Imports & Setup ───────────────────────────────
import time, torch
import numpy as np
from datasets import load_dataset
from transformers import (
    BertTokenizer, BertForSequenceClassification,
    Trainer, TrainingArguments, DataCollatorWithPadding
)
from peft import get_peft_model, LoraConfig, TaskType
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")


# ── CELL 3: Load & Subset Dataset ────────────────────────
from datasets import load_dataset

# Fix: newer HuggingFace requires namespace/name format
raw = load_dataset("stanfordnlp/imdb")

# Use a small subset so Colab doesn't time out
train_subset = raw["train"].shuffle(seed=42).select(range(1600))
val_subset   = raw["test"].shuffle(seed=42).select(range(200))
test_subset  = raw["test"].shuffle(seed=42).select(range(200, 400))

print(f"Train: {len(train_subset)}, Val: {len(val_subset)}, Test: {len(test_subset)}")

# ── CELL 4: Tokenize ─────────────────────────────────────
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, max_length=256)

train_tok = train_subset.map(tokenize, batched=True)
val_tok   = val_subset.map(tokenize, batched=True)
test_tok  = test_subset.map(tokenize, batched=True)

# HuggingFace Trainer expects "label" not "labels"
for ds in [train_tok, val_tok, test_tok]:
    ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

collator = DataCollatorWithPadding(tokenizer)

# ── CELL 5: Metrics helper ────────────────────────────────
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    acc = accuracy_score(labels, preds)
    p, r, f1, _ = precision_recall_fscore_support(labels, preds, average="binary")
    return {"accuracy": acc, "precision": p, "recall": r, "f1": f1}

# ── CELL 6: Training args factory ────────────────────────
def get_args(output_dir, epochs=2):
    return TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=epochs,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=16,
        eval_strategy="epoch",      # Changed from evaluation_strategy
        save_strategy="no",
        logging_steps=50,
        fp16=(DEVICE == "cuda"),
        report_to="none",
    )

results = {}

Using device: cpu
Train: 1600, Val: 200, Test: 200

In [21]:
from transformers import BertTokenizer

# Fix common dataset / environment issues before training
import datasets.config as ds_config
ds_config.TORCHVISION_AVAILABLE = False


if "tokenizer" not in globals():
    tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

raw = None
for name in ["stanfordnlp/imdb", "imdb"]:
    try:
        raw = load_dataset(name)
        print(f"Loaded dataset: {name}")
        break
    except Exception as exc:
        print(f"Failed to load {name}: {exc}")

if raw is None:
    raise RuntimeError("Could not load the IMDb dataset. Check the dataset name and network access.")

train_subset = raw["train"].shuffle(seed=42).select(range(1600))
val_subset = raw["test"].shuffle(seed=42).select(range(200))
test_subset = raw["test"].shuffle(seed=42).select(range(200, 400))

print(f"Train: {len(train_subset)}, Val: {len(val_subset)}, Test: {len(test_subset)}")

def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, max_length=256)

train_tok = train_subset.map(tokenize, batched=True)
val_tok = val_subset.map(tokenize, batched=True)
test_tok = test_subset.map(tokenize, batched=True)

for ds in [train_tok, val_tok, test_tok]:
    ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

collator = DataCollatorWithPadding(tokenizer)

Loaded dataset: stanfordnlp/imdb
Train: 1600, Val: 200, Test: 200

In [22]:
import sys

# Prevent datasets from triggering the broken VideoReader import
mods_to_remove = [k for k in sys.modules if "torchvision" in k]
for m in mods_to_remove:
    del sys.modules[m]

# Also tell datasets torchvision isn't available
import datasets.config as ds_config
ds_config.TORCHVISION_AVAILABLE = False

print("torchvision unloaded — safe to train")

torchvision unloaded — safe to train

In [23]:
import transformers
print(transformers.__version__)

4.57.6

In [24]:
# ════════════════════════════════════════════════════════════
# STEP 2 — Traditional Fine-Tuning (all params updated)
# ════════════════════════════════════════════════════════════
print("\n=== TRADITIONAL FINE-TUNING ===")

model_trad = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased", num_labels=2
)

trainer_trad = Trainer(
    model=model_trad,
    args=get_args("./results_traditional"),
    train_dataset=train_tok,
    eval_dataset=val_tok,
    data_collator=collator,
    compute_metrics=compute_metrics,
)

t0 = time.time()
trainer_trad.train()
trad_time = time.time() - t0

trad_metrics = trainer_trad.evaluate(test_tok)
trad_params  = sum(p.numel() for p in model_trad.parameters())

results["Traditional"] = {
    "time_s": round(trad_time, 1),
    "trainable_params": trad_params,
    **trad_metrics
}
print(f"Done in {trad_time:.1f}s | Params: {trad_params:,}")
print(trad_metrics)

=== TRADITIONAL FINE-TUNING ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Done in 471.4s | Params: 109,483,778
{'eval_loss': 0.33739447593688965, 'eval_accuracy': 0.9, 'eval_precision': 0.8928571428571429, 'eval_recall': 0.9259259259259259, 'eval_f1': 0.9090909090909091, 'eval_runtime': 5.9252, 'eval_samples_per_second': 33.754, 'eval_steps_per_second': 2.194, 'epoch': 2.0}

In [25]:
import subprocess, sys
result = subprocess.run(
    [sys.executable, "-m", "pip", "install", "numpy<2", "--force-reinstall", "--no-deps"],
    capture_output=True, text=True
)
print(result.stdout[-2000:])
print(result.stderr[-2000:])

Collecting numpy<2
  Using cached numpy-1.26.4-cp312-cp312-macosx_10_9_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-macosx_10_9_x86_64.whl (20.3 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy None

isimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 684, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/req/req_uninstall.py", line 523, in from_dist
    for path in uninstallation_paths(dist):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/req/req_uninstall.py", line 49, in unique
    for item in fn(*args, **kw):
                ^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/req/req_uninstall.py", line 77, in uninstallation_paths
    raise UninstallMissingRecord(distribution=dist)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/exceptions.py", line 769, in __init__
    dep = f"{distribution.raw_name}=={distribution.version}"
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_dists.py", line 174, in version
    return parse_version(version)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_vendor/packaging/version.py", line 122, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/Users/mthabisimunyariri/Desktop/ML Engineering Stuff /.venv/lib/python3.12/site-packages/pip/_vendor/packaging/version.py", line 438, in __init__
    raise InvalidVersion(f"Invalid version: {version!r}")
pip._vendor.packaging.version.InvalidVersion: Invalid version: '1.26.4 2'

In [26]:
# ════════════════════════════════════════════════════════════
# STEP 3 — LoRA Fine-Tuning
# ════════════════════════════════════════════════════════════
print("\n=== LoRA FINE-TUNING ===")

base_lora = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased", num_labels=2
)

lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=8,                          # rank of update matrices
    lora_alpha=16,                # scaling factor
    target_modules=["query", "value"],   # attention layers only
    lora_dropout=0.1,
    bias="none",
)

model_lora = get_peft_model(base_lora, lora_config)
model_lora.print_trainable_parameters()

trainer_lora = Trainer(
    model=model_lora,
    args=get_args("./results_lora"),
    train_dataset=train_tok,
    eval_dataset=val_tok,
    data_collator=collator,
    compute_metrics=compute_metrics,
)

t0 = time.time()
trainer_lora.train()
lora_time = time.time() - t0

lora_metrics = trainer_lora.evaluate(test_tok)
lora_trainable = sum(p.numel() for p in model_lora.parameters() if p.requires_grad)

results["LoRA"] = {
    "time_s": round(lora_time, 1),
    "trainable_params": lora_trainable,
    **lora_metrics
}
print(f"Done in {lora_time:.1f}s | Trainable params: {lora_trainable:,}")
print(lora_metrics)

=== LoRA FINE-TUNING ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

trainable params: 296,450 || all params: 109,780,228 || trainable%: 0.2700

Done in 313.7s | Trainable params: 296,450
{'eval_loss': 0.6567772626876831, 'eval_accuracy': 0.72, 'eval_precision': 0.7452830188679245, 'eval_recall': 0.7314814814814815, 'eval_f1': 0.7383177570093458, 'eval_runtime': 7.0708, 'eval_samples_per_second': 28.285, 'eval_steps_per_second': 1.839, 'epoch': 2.0}

In [28]:
import torch

print(torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

False

In [ ]:
#THis code wont run because the CUDA device is not available in this environment. You may need to run this code on a machine with a compatible GPU and CUDA installed.
# ════════════════════════════════════════════════════════════
# STEP 4 — QLoRA Fine-Tuning (4-bit quantization + LoRA)
# ════════════════════════════════════════════════════════════
print("\n=== QLoRA FINE-TUNING ===")

from transformers import BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# Note: BitsAndBytes 4-bit works best on GPU; falls back gracefully on CPU
try:
    base_qlora = BertForSequenceClassification.from_pretrained(
        "bert-base-uncased",
        num_labels=2,
        quantization_config=bnb_config,
        device_map="auto",
    )
    qlora_config = LoraConfig(
        task_type=TaskType.SEQ_CLS,
        r=8,
        lora_alpha=16,
        target_modules=["query", "value"],
        lora_dropout=0.1,
        bias="none",
    )
    model_qlora = get_peft_model(base_qlora, qlora_config)
    model_qlora.print_trainable_parameters()
except Exception as e:
    print(f"4-bit load failed ({e}), falling back to 8-bit load_in_8bit")
    base_qlora = BertForSequenceClassification.from_pretrained(
        "bert-base-uncased", num_labels=2, load_in_8bit=True, device_map="auto"
    )
    model_qlora = get_peft_model(base_qlora, qlora_config)

qlora_args = get_args("./results_qlora")
# fp16 conflicts with 4-bit; disable
qlora_args.fp16 = False

trainer_qlora = Trainer(
    model=model_qlora,
    args=qlora_args,
    train_dataset=train_tok,
    eval_dataset=val_tok,
    data_collator=collator,
    compute_metrics=compute_metrics,
)

t0 = time.time()
trainer_qlora.train()
qlora_time = time.time() - t0

qlora_metrics = trainer_qlora.evaluate(test_tok)
qlora_trainable = sum(p.numel() for p in model_qlora.parameters() if p.requires_grad)

results["QLoRA"] = {
    "time_s": round(qlora_time, 1),
    "trainable_params": qlora_trainable,
    **qlora_metrics
}
print(f"Done in {qlora_time:.1f}s | Trainable params: {qlora_trainable:,}")
print(qlora_metrics)

In [29]:








# ════════════════════════════════════════════════════════════
# STEP 5 — Compare Results
# ════════════════════════════════════════════════════════════
import pandas as pd

summary = []
for method, r in results.items():
    summary.append({
        "Method":            method,
        "Train Time (s)":    r.get("time_s"),
        "Trainable Params":  f"{r.get('trainable_params', 0):,}",
        "Accuracy":          round(r.get("eval_accuracy", 0), 4),
        "F1":                round(r.get("eval_f1", 0), 4),
        "Precision":         round(r.get("eval_precision", 0), 4),
        "Recall":            round(r.get("eval_recall", 0), 4),
    })

df = pd.DataFrame(summary)
print("\n=== COMPARISON TABLE ===")
print(df.to_string(index=False))

=== COMPARISON TABLE ===
     Method  Train Time (s) Trainable Params  Accuracy     F1  Precision  Recall
Traditional           471.4      109,483,778      0.90 0.9091     0.8929  0.9259
       LoRA           313.7          296,450      0.72 0.7383     0.7453  0.7315